config/routes.rb
Rails.application.routes.draw do
  resources :blog_indices
  devise_for :users
  resources :blog_images, :only => [:create]

  match 'blog_indices/aboutme' , :via => :get
  root to: 'blog_indices#index'









end

app/models/blog_user.rb
class BlogUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/blog_users_controller.rb
class BlogUsersController < ApplicationController
  before_action :set_blog_user, only: [:show, :edit, :update, :destroy]

  # GET /blog_users
  # GET /blog_users.json
  def index
    @blog_users = BlogUser.all
  end

  # GET /blog_users/1
  # GET /blog_users/1.json
  def show
  end

  # GET /blog_users/new
  def new
    @blog_user = BlogUser.new
  end

  # GET /blog_users/1/edit
  def edit
  end

  # POST /blog_users
  # POST /blog_users.json
  def create
    @blog_user = BlogUser.new(blog_user_params)

    respond_to do |format|
      if @blog_user.save
        format.html { redirect_to @blog_user, notice: 'Blog user was successfully created.' }
        format.json { render :show, status: :created, location: @blog_user }
      else
        format.html { render :new }
        format.json { render json: @blog_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_users/1
  # PATCH/PUT /blog_users/1.json
  def update
    respond_to do |format|
      if @blog_user.update(blog_user_params)
        format.html { redirect_to @blog_user, notice: 'Blog user was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_user }
      else
        format.html { render :edit }
        format.json { render json: @blog_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_users/1
  # DELETE /blog_users/1.json
  def destroy
    @blog_user.destroy
    respond_to do |format|
      format.html { redirect_to blog_users_url, notice: 'Blog user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_user
      @blog_user = BlogUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_user_params
      params[:blog_user]
    end
end

app/helpers/blog_users_helper.rb
module BlogUsersHelper
end

app/views/blog_users/_form.html.erb
<%= form_for(@blog_user) do |f| %>
  <% if @blog_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_user.errors.count, "error") %> prohibited this blog_user from being saved:</h2>

      <ul>
      <% @blog_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_users/edit.html.erb
<h1>Editing blog_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_user %> |
<%= link_to 'Back', blog_users_path %>

app/views/blog_users/index.html.erb
<h1>Listing blog_users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_users.each do |blog_user| %>
      <tr>
        <td><%= link_to 'Show', blog_user %></td>
        <td><%= link_to 'Edit', edit_blog_user_path(blog_user) %></td>
        <td><%= link_to 'Destroy', blog_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog user', new_blog_user_path %>

app/views/blog_users/new.html.erb
<h1>New blog_user</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_users_path %>

app/views/blog_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blog_user_path(@blog_user) %> |
<%= link_to 'Back', blog_users_path %>