config/routes.rb
Rails.application.routes.draw do
  resources :blog_indices
  devise_for :users
  resources :blog_images, :only => [:create]

  match 'blog_indices/aboutme' , :via => :get
  root to: 'blog_indices#index'









end

app/controllers/blog_indices_controller.rb
class BlogIndicesController < ApplicationController
  # ユーザがログインしていないとにアクセスできないアクション
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy ]
  def new
    commonLog("new", "blog_index.id", "all","start")
    #blog_indexのidをのみ登録する。
    @blog_index=BlogIndex.create()
    #blog_text初期化
    @result_blog_texts=Array.new()
    @result_blog_texts.push(BlogText.new(text:""))
    #form_tagに埋め込むコミット先のURLを指定
    @path="/blog_indices"
    #form_tagに埋め込むmethodを指定
    @method="post"
    logger.debug(@result_blog_texts)
    logger.debug(@blog_index)
    commonLog("new", "blog_index.id", "all","end")
  end

  def edit
    commonLog("edit", "blog_index.id", params[:id] ,"start")
    #指定のidのtitleを取得する。
    @blog_index=BlogIndex.fild_by_detail(params[:id])[0]
    @result_blog_index_id=BlogIndex.fild_by_detail(params[:id])[0]
    #blog_idに紐づくtext,imageを取得する。
    commonSelect( @result_blog_index_id)
    #form_tagに埋め込むコミット先のURLを指定
    
    @path="/blog_indices/#{@result_blog_index_id.id}"
    #form_tagに埋め込むmethodを指定
    @method="put"
    logger.debug( @result_blog_texts)
    logger.debug( @result_blog_images)
    commonLog("edit", "blog_index.id", params[:id] ,"end")
  end

  def index
    commonLog("index", "blog_index.id", "all","start")
    #blog_indexのidをすべて取得する。
    @result_blog_index_title=BlogIndex.select_title()
    @result_blog_index_id=BlogIndex.select_id()
    #blog_idに紐づくtext,imageを取得する。
    logger.debug(@result_blog_index_id)
    commonSelect(@result_blog_index_id)
    commonLog("index", "blog_index.id", "all","end")
  end

  def show
    commonLog("show", "blog_index.id", params[:id],"start")
    #指定のidのtitleを取得する。
    @result_blog_index_id=BlogIndex.fild_by_detail(params[:id])
    #blog_idに紐づくtext,imageを取得する。
    commonSelect( @result_blog_index_id)
    logger.debug( @result_blog_index_id)
    logger.debug( @result_blog_texts)
    logger.debug( @result_blog_images)

    commonLog("show", "blog_index.id", params[:id],"end")
  end

  def create
    #トランザクション開始
    begin
      commonLog("create", "blog_index.id", "new","start")
      #paramの取得
      blog_title=params[:blog_title]
      blog_texts=params[:blog_texts]
      blog_index_id=params[:blog_index_id]

      #blog_images=params[:counter]
      BlogIndex.transaction do
      #登録された画像の個数
        blog_images_controller=BlogImagesController.new
        blog_images=blog_images_controller.show(blog_index_id)

        #blog_indexを登録する。
        @blog_index_result = BlogIndex.update_detail(blog_index_id,blog_title,blog_images.size ,blog_texts.size)

        #blogtextes_controllerのcreateを呼び出す。
        blog_texts_controller=BlogTextsController.new
        blog_texts_controller.create(blog_texts,blog_index_id)
      end
      commonLog("create", "blog_index.id", "new","end")
    end
  rescue => e
    p e
  ensure
    redirect_to blog_indices_path

    end

  def update
    #トランザクション開始
    begin
      commonLog("update", "blog_index.id", params[:id] ,"start")
      BlogIndex.transaction do
      #paramの取得
        id=params[:id]
        blog_title=params[:blog_title]
        blog_texts=params[:blog_texts]

        #blog_titleをアップデートする。
        @title_update_num=BlogIndex.update_title(id,blog_title)

        #blogtextes_controllerのcreateを呼び出す。
        blog_texts_controller=BlogTextsController.new
        @text_update_num=blog_texts_controller.update(id,blog_texts)

      end
      commonLog("edit", "blog_index.id", params[:id] ,"end")
    end
  rescue => e
    p e
  ensure
    redirect_to blog_indices_path
    end

  def destroy
    #トランザクション開始
    begin
      commonLog("destroy", "blog_index.id", params[:id] ,"start")
      BlogIndex.transaction do
      #DBから値の取得
        @dl_result_blog_index=BlogIndex.destroy_all(id:params[:id])
      end
      commonLog("destroy", "blog_index.id", params[:id] ,"end")
    #redirect_to :back
    end
  rescue => e
    p e
  ensure
    redirect_to blog_indices_path
    end

  def commonSelect(result_blog_index_id)
    #blogtextes_controllerのindexを呼び出す。
    blog_texts_controller=BlogTextsController.new
    @result_blog_texts=blog_texts_controller.index(@result_blog_index_id)
    #blogimages_controllerのindexを呼び出す。
    blog_images_controller=BlogImagesController.new
    @result_blog_images=blog_images_controller.index(@result_blog_index_id)
  end

  def commonLog(method, index_id, object,timing)
    logger.debug("#{Time.now} blog_indices_controler #{method} #{timing}!!")
    logger.debug("method:#{method} #{object}:#{index_id}")
  end
end

app/helpers/blog_indices_helper.rb
module BlogIndicesHelper
end

app/views/blog_indices/_form.html.erb
<%= form_tag(@path, multipart: true, method: @method) do %>


<div class="input" style="float:left;">
	<!--タイトル入力欄 -->
	<%#= @blog_index.id%>
	<div class="title_form">
		<%= label_tag "題名" %>
		<br>
		<%= text_field_tag "blog_title" ,@blog_index.title, :onKeyUp => "ShowHtml( 'inputTiltle' , value );" %>
	</div>
	<br>
	<div class="text_form">
		<%= label_tag "本文" %>
		<br>
		<%= text_area_tag "blog_texts[0]" ,@result_blog_texts[0].text, :onKeyUp => "ShowHtml( 'inputText' , value );" %>
	</div>

	<input type="hidden" id="blog_index_id" name="blog_index_id" value= <%= @blog_index.id %> />

	<!--送信ボタン -->
	<div class="actions">
		<%= submit_tag "送信" , disable_with: "送信中...",id: "commit" %>
	</div>

</div>
<% end %>

<!--画像登録用フォーム -->
<%= form_tag('/blog_images', method: "post",id: "blog_images",name:"blog_images", :multipart => true) do %>
<!--画像登録用ボタン-->
画像追加
<br>
<input type="file" accept="image/*" id="blog_images" name="blog_images" />
<input type="hidden" id="blog_index_id" name="blog_index_id" value= <%= @blog_index.id %> />

<% end %>

<!--記事プレビュー欄 -->
<!--タイトルプレビュー-->
<div id=sammay>
	<div id="preview" style="float:left;">
		記事プレビュー欄
		<h1><div id='inputTiltle'></div></h1>
		<div id='inputText'></div>
		<div id='inputImage'></div>
	</div>
</div>

<!--隠しパラメータ-->
<input type="hidden" id="counter" value= 0 />

<!-- JavaScript -->
<!-- 記事プレビュー用JS -->
<script type="text/javascript">
	function ShowHtml(idn, str) {
		document.getElementById(idn).innerHTML = str.replace(/[\n\r]/g, "<br />");
	}
</script>

<!-- 画像登録用JS -->
<script>
	var counter = 0
$(function() {
$('#blog_images').change(function() {
$('#blog_images').ajaxSubmit({
success: function() {
var insText = '<img src=<%= "/images/#{Time.now.strftime("%Y")}/#{@blog_index.id}" %>/' + counter + '.jpg>';
//マークアップを入れる箇所を決定する。
var area = document.getElementById("blog_texts_0");
var inputedText = document.getElementById("blog_texts_0").value;
var inputedTextLn = inputedText.length;
var startPosition = area.selectionStart;

var bfInsText = inputedText.substr(0, startPosition);
var afInsedText = inputedText.substr(startPosition, inputedTextLn);

//textarea内にマークアップを追加
document.getElementById('blog_texts_0').value = bfInsText + insText + afInsedText;
//counterをインクリメントする。
counter=document.getElementById('counter').value ;
counter =  parseInt(counter) + 1 ;
document.getElementById('counter').value = counter;

},
});
});
});

</script>

app/views/blog_indices/aboutme.html.erb
<table>
	<thead>
		<tr>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<div id="title">
			<h3>BLOG MAKE BLOGとDef_Drankについて</h3>
			プログラミングの勉強中の
			<a href="https://twitter.com/Def_Drank" target="_blank">@Def_Drank</a>です。
			<br>
			勉強の一環でブログサイトを作ってみようという試み。構築のすったもんだを記事に書いていこうという魂胆。
			<br>
			叱咤激励、バグ報告、お仕事のお話など頂ける...。そんな奇特な方がいらっしゃいましたら、大変お手数ですが、
			<br>
			<a href="https://twitter.com/Def_Drank" target="_blank">@Def_Drank</a> へお願いします。しっぽ振って喜びます。
			<br>
			勉強中ゆえに簡単なホームページ制作などございましたら、勉強の一環になりますので、
			<br>
			ぜひご協力させていただきたいと考えていますのでお気軽にご相談いただければと思います。
		</div>
	</tbody>
</table>

app/views/blog_indices/edit.html.erb
<h1>Editing blog_index</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_index %> |
<%= link_to 'Back', blog_indices_path %>

app/views/blog_indices/index.html.erb
<% @id_num = 0 %> <!--記事一覧表示処理 -->
<!--タイトル表示-->
<% for id_num in 0..@result_blog_index_id.size-1 do  %>

<%= link_to blog_index_path(@result_blog_index_title[id_num].id), class: "showlink" do%>

<!--div class="showlink"-->
<h1>
<div class="title">
	<%= @result_blog_index_title[id_num].title%>
</div></h1>

<!--本文表示  blog_indexのIDと一致するindex_idを持つimgaeを一つだけ表示する。-->
<% for image_num in 0..@result_blog_images.size-1 do  %>
<% if @result_blog_images[image_num].blog_index_id == @result_blog_index_title[id_num].id %>
<div class="sammary_image">
	<%= image_tag @result_blog_images[image_num].image, class: "thumbnail-img" ,align: "left" %>
</div>
<% break %>
<% end %>
<% end %>

<!--本文表示  blog_indexのIDと一致するindex_idを持つtextを一つだけ表示する。-->
<% for text_num in 0..@result_blog_texts.size-1 do  %>
<% if @result_blog_texts[text_num].blog_index_id == @result_blog_index_title[id_num].id %>
<div class="sammary_text">
	<%= br(tag_erase(@result_blog_texts[text_num].text).html_safe) %>
</div>
<% break %>
<% end %>
<% end %>

<!-- ログイン中であれば削除ボタン、編集ボタンを表示する。 -->
<% if signed_in? %>
<%= link_to '編集', edit_blog_index_path(@result_blog_index_title[id_num].id) %> |
<%= link_to "削除", blog_index_path(@result_blog_index_title[id_num].id), :method => :delete %>
<% end %>

<% end %>
<% @id_num = @id_num +1  %>
<% end %>

<!-- ログイン中であれば削除ボタン、編集ボタンを表示する。 -->
<% if signed_in? %>
<%= link_to '新規作成', new_blog_index_path %>
<% end %>

<!--記事一覧表示処理ここまで -->

app/views/blog_indices/new.html.erb
<h1>記事投稿</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_indices_path %>

app/views/blog_indices/show.html.erb
<div class=title>
	<h1><%= @result_blog_index_id[0].title %></h1>
</div>

<% for num in 0..@result_blog_index_id[0].num_of_text-1 do  %>
<% if @result_blog_texts[num].class != NilClass  %>
<%= br(@result_blog_texts[num].text.html_safe) %>
<% end %>
<% end %>

<br clear="left">
<%#= link_to '更新', edit_blog_index_path(@blog_index) %> |
<%= link_to '戻る', blog_indices_path, :id => 'blog_indeices'%>